# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "phormat"

behind_proxy: true

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

plugins:
    Ajax:
        content_type: 'application/json'
    "Auth::Github":
        client_id: ''
        client_secret: ''
    "Auth::Twitter":
        consumer_key: ''
        consumer_secret: ''
        callback_url: http://127.0.0.1/auth/twitter/callback
    Database:
        driver: "SQLite"
        database: ":memory:"
    Facebook:
        application:
            app_id: ''
            secret: ''
        permissions:
            - create_event
            - email
            - offline_access
            - publish_stream
            - rsvp_event


session: "YAML"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
    template_toolkit:
        start_tag: '[%'
        end_tag:   '%]'

